### ISSUE TITLE
Collations having issue while creating migration.

### ISSUE THREAD

**Issue by ateequrrahman97** [kitloong/laravel-migrations-generator#66] opened 2021-12-22 14:30 UTC
![image](https://user-images.githubusercontent.com/74288984/147108053-a25a06ab-6494-4db0-881f-03ef989109a8.png)
@kitloong

**Comment by kitloong** [comment] 2021-12-25 03:17
Hi @ateequrrahman97 

Thank you for reporting. I am not sure but looks like you have collation error in your existing table?
https://stackoverflow.com/questions/1008287/illegal-mix-of-collations-mysql-error

I am afraid it is not the kind of error the generator could handle.

I will close this issue now.

If after confirmation this is the error caused by the generator, please provide the full stack trace and the table DDL so that I could reproduce it.

**Closed by kitloong** 2021-12-25 03:17 UTC
