### ISSUE TITLE
Create table migrations generated with wrong column types

### ISSUE THREAD

**Issue by CaraesNaur** [kitloong/laravel-migrations-generator#193] opened 2023-12-09 15:17 UTC
**Describe the bug**
Regression: some column types in migrations do not match those of the basis database table.

* `bigint` becomes integer
* `smallint` becomes integer
* `datetime` becomes string
* `decimal` becomes float

**To Reproduce**
1. Create table:

```
    CREATE TABLE `file_visuals` (
      `id` bigint unsigned NOT NULL AUTO_INCREMENT,
      `organization_id` bigint unsigned NOT NULL,
      `parent_company_id` bigint unsigned NOT NULL,
      `brand_owner_id` bigint unsigned NOT NULL,
      `brand_id` bigint unsigned NOT NULL,
      `subbrand_id` bigint unsigned DEFAULT NULL,
      `created_by` bigint unsigned NOT NULL,
      `owned_by` bigint unsigned DEFAULT NULL,
      `updated_by` bigint unsigned DEFAULT NULL,
      `deleted_by` bigint unsigned DEFAULT NULL,
      `file_id` bigint unsigned NOT NULL,
      `custom_orientation_id` bigint unsigned DEFAULT NULL,
      `frame_number` smallint unsigned NOT NULL DEFAULT '1',
      `frames_count` smallint unsigned NOT NULL DEFAULT '1',
      `total_planes` smallint unsigned NOT NULL DEFAULT '1',
      `created_at` datetime NOT NULL,
      `updated_at` datetime DEFAULT NULL,
      `deleted_at` datetime DEFAULT NULL,
      `dimension_x` decimal(12,6) NOT NULL DEFAULT '0.000000',
      `dimension_y` decimal(12,6) NOT NULL DEFAULT '0.000000',
      `play_duration` decimal(8,3) unsigned DEFAULT '0.000',
      `plunge_angle` decimal(12,6) NOT NULL DEFAULT '0.000000',
      PRIMARY KEY (`id`),
      KEY `IDX_file_visuals_organization_id` (`organization_id`),
      KEY `IDX_file_visuals_parent_company_id` (`parent_company_id`),
      KEY `IDX_file_visuals_brand_owner_id` (`brand_owner_id`),
      KEY `IDX_file_visuals_brand_id` (`brand_id`),
      KEY `IDX_file_visuals_subbrand_id` (`subbrand_id`),
      KEY `IDX_file_visuals_created_by` (`created_by`),
      KEY `IDX_file_visuals_owned_by` (`owned_by`),
      KEY `IDX_file_visuals_updated_by` (`updated_by`),
      KEY `IDX_file_visuals_deleted_by` (`deleted_by`),
      KEY `IDX_file_visuals_file_id` (`file_id`),
      KEY `IDX_file_visuals_custom_orientation_id` (`custom_orientation_id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
```

3. Run `php artisan migrate:generate -n -vvv --tables=file_visuals`

The migration run today contains:

```
    // 2023_12_08_175711_create_file_visuals_table.php
    public function up()
    {
        Schema::create('file_visuals', function (Blueprint $table) {
            $table->increments('id');
            $table->unsignedInteger('organization_id')->index('IDX_file_visuals_organization_id');
            $table->unsignedInteger('parent_company_id')->index('IDX_file_visuals_parent_company_id');
            $table->unsignedInteger('brand_owner_id')->index('IDX_file_visuals_brand_owner_id');
            $table->unsignedInteger('brand_id')->index('IDX_file_visuals_brand_id');
            $table->unsignedInteger('subbrand_id')->nullable()->index('IDX_file_visuals_subbrand_id');
            $table->unsignedInteger('created_by')->index('IDX_file_visuals_created_by');
            $table->unsignedInteger('owned_by')->nullable()->index('IDX_file_visuals_owned_by');
            $table->unsignedInteger('updated_by')->nullable()->index('IDX_file_visuals_updated_by');
            $table->unsignedInteger('deleted_by')->nullable()->index('IDX_file_visuals_deleted_by');
            $table->unsignedInteger('file_id')->index('IDX_file_visuals_file_id');
            $table->unsignedInteger('custom_orientation_id')->nullable()->index('IDX_file_visuals_custom_orientation_id');
            $table->unsignedInteger('frame_number')->default(1);
            $table->unsignedInteger('frames_count')->default(1);
            $table->unsignedInteger('total_planes')->default(1);
            $table->string('created_at', 0);
            $table->string('updated_at', 0)->nullable();
            $table->string('deleted_at', 0)->nullable();
            $table->float('dimension_x', 12, 6)->default(0);
            $table->float('dimension_y', 12, 6)->default(0);
            $table->float('play_duration', 8, 3)->unsigned()->nullable()->default(0);
            $table->float('plunge_angle', 12, 6)->default(0);
        });
    }
```
**Expected behavior**

This is the relevant snip from an older version of the same migration:

```
    // 2023_09_22_211715_create_file_visuals_table.php
    public function up()
    {
        Schema::create('file_visuals', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->unsignedBigInteger('organization_id')->index('IDX_file_visuals_organization_id');
            $table->unsignedBigInteger('parent_company_id')->index('IDX_file_visuals_parent_company_id');
            $table->unsignedBigInteger('brand_owner_id')->index('IDX_file_visuals_brand_owner_id');
            $table->unsignedBigInteger('brand_id')->index('IDX_file_visuals_brand_id');
            $table->unsignedBigInteger('subbrand_id')->nullable()->index('IDX_file_visuals_subbrand_id');
            $table->unsignedBigInteger('created_by')->index('IDX_file_visuals_created_by');
            $table->unsignedBigInteger('owned_by')->index('IDX_file_visuals_owned_by');
            $table->unsignedBigInteger('updated_by')->nullable()->index('IDX_file_visuals_updated_by');
            $table->unsignedBigInteger('deleted_by')->nullable()->index('IDX_file_visuals_deleted_by');
            $table->unsignedBigInteger('file_id')->index('IDX_file_visuals_file_id');
            $table->unsignedBigInteger('custom_orientation_id')->nullable()->index('IDX_file_visuals_custom_orientation_id');
            $table->unsignedSmallInteger('frame_number')->default(1);
            $table->unsignedSmallInteger('frames_count')->default(1);
            $table->unsignedSmallInteger('total_planes')->default(1);
            $table->dateTime('created_at');
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();
            $table->decimal('dimension_x', 12, 6)->default(0);
            $table->decimal('dimension_y', 12, 6)->default(0);
            $table->unsignedDecimal('play_duration', 8, 3)->nullable()->default(0);
            $table->decimal('plunge_angle', 12, 6)->default(0);
        });
    }
```

**Screenshots**

![image](https://github.com/kitloong/laravel-migrations-generator/assets/544558/bec31842-17f7-40d2-aab5-e933226248fc)

Old (expected) on the left, new (wrong) on the right.

(Making `owned_by` nullable and `play_duration` unsigned are deliberate, expected differences.)

**Details (please complete the following information):**
 - DB: MySQL
 - DB Version: 8.0.32-0ubuntu0.22.04.2 for Linux on x86_64 ((Ubuntu))
 - Laravel Version:  9.52.15
 - PHP Version: 8.1.2-1ubuntu2.13
 - Migrations Generator Version: 6.10.0
 - Doctrine DBAL Version: 3.6.6

**Additional context**

**Comment by kitloong** [comment] 2023-12-09 15:58
Hi @CaraesNaur , thank you for your details.

I repeat your steps in a new Laravel project, and here is my generated migration:

```
        Schema::create('file_visuals', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->unsignedBigInteger('organization_id')->index('IDX_file_visuals_organization_id');
            $table->unsignedBigInteger('parent_company_id')->index('IDX_file_visuals_parent_company_id');
            $table->unsignedBigInteger('brand_owner_id')->index('IDX_file_visuals_brand_owner_id');
            $table->unsignedBigInteger('brand_id')->index('IDX_file_visuals_brand_id');
            $table->unsignedBigInteger('subbrand_id')->nullable()->index('IDX_file_visuals_subbrand_id');
            $table->unsignedBigInteger('created_by')->index('IDX_file_visuals_created_by');
            $table->unsignedBigInteger('owned_by')->nullable()->index('IDX_file_visuals_owned_by');
            $table->unsignedBigInteger('updated_by')->nullable()->index('IDX_file_visuals_updated_by');
            $table->unsignedBigInteger('deleted_by')->nullable()->index('IDX_file_visuals_deleted_by');
            $table->unsignedBigInteger('file_id')->index('IDX_file_visuals_file_id');
            $table->unsignedBigInteger('custom_orientation_id')->nullable()->index('IDX_file_visuals_custom_orientation_id');
            $table->unsignedSmallInteger('frame_number')->default(1);
            $table->unsignedSmallInteger('frames_count')->default(1);
            $table->unsignedSmallInteger('total_planes')->default(1);
            $table->dateTime('created_at');
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();
            $table->decimal('dimension_x', 12, 6)->default(0);
            $table->decimal('dimension_y', 12, 6)->default(0);
            $table->unsignedDecimal('play_duration', 8, 3)->nullable()->default(0);
            $table->decimal('plunge_angle', 12, 6)->default(0);
        });
```

Could you check your `composer.json` there is a different migration generator installed?

If you don't mind you could post your `composer.json` here for checking purposes.

**Comment by CaraesNaur** [comment] 2023-12-09 18:57
The only other generator present is krlove/eloquent-model-generator.  I use both via scripts, as I have ~200 models/tables to deal with.

```
$ grep -Pi '(migrat|generat)' composer.*
composer.json:        "kitloong/laravel-migrations-generator": "^6.6",
composer.json:        "krlove/eloquent-model-generator": "^2.0@dev",
composer.json:            "@php artisan key:generate --ansi"
composer.lock:        "This file is @generated automatically"
composer.lock:                "ext-bcmath": "Needed for generation of some types of barcodes",
composer.lock:            "description": "PHP library generating PDF files from UTF-8 encoded HTML",
composer.lock:            "description": "🛠  Nette Utils: lightweight utilities for string & array manipulation, image handling, safe JSON encoding/decoding, validation, slug or strong password generating etc.",
composer.lock:            "description": "Generate a new Laravel database seed file based on data from the existing database table.",
composer.lock:                "generators",
composer.lock:                "ext-libsodium": "Provides a modern crypto API that can be used to generate random bytes."
composer.lock:                "ext-uuid": "Enables the use of PeclUuidTimeGenerator and PeclUuidRandomGenerator.",
composer.lock:            "description": "A PHP library for generating and working with universally unique identifiers (UUIDs).",
composer.lock:            "description": "Provides an object-oriented API to generate and represent UIDs",
composer.lock:                "ext-dom": "Required by Faker\\Provider\\HtmlLorem for generating random HTML.",
composer.lock:                "ext-iconv": "Required by Faker\\Provider\\ru_RU\\Text::realText() for generating real Russian text.",
composer.lock:            "description": "Faker is a PHP library that generates fake data for you.",
composer.lock:            "name": "kitloong/laravel-migrations-generator",
composer.lock:                "url": "https://github.com/kitloong/laravel-migrations-generator.git",
composer.lock:                "url": "https://api.github.com/repos/kitloong/laravel-migrations-generator/zipball/116f50fab918b7f1363a40ebd954ce250f6aedcd",
composer.lock:                        "KitLoong\\MigrationsGenerator\\MigrationsGeneratorServiceProvider"
composer.lock:                    "KitLoong\\MigrationsGenerator\\": "src"
composer.lock:            "description": "Generates Laravel Migrations from an existing database",
composer.lock:                "generator",
composer.lock:                "migration",
composer.lock:                "migrations"
composer.lock:                "issues": "https://github.com/kitloong/laravel-migrations-generator/issues",
composer.lock:                "source": "https://github.com/kitloong/laravel-migrations-generator/tree/v6.10.0"
composer.lock:            "name": "krlove/code-generator",
composer.lock:                "url": "https://github.com/krlove/code-generator.git",
composer.lock:                "url": "https://api.github.com/repos/krlove/code-generator/zipball/1ac521f5ef79a376282e3315ba6a13a83c63fb9a",
composer.lock:                    "Krlove\\CodeGenerator\\": "src/"
composer.lock:            "description": "Code Generator",
composer.lock:                "issues": "https://github.com/krlove/code-generator/issues",
composer.lock:                "source": "https://github.com/krlove/code-generator/tree/1.0.1"
composer.lock:            "name": "krlove/eloquent-model-generator",
composer.lock:                "url": "https://github.com/krlove/eloquent-model-generator.git",
composer.lock:                "url": "https://api.github.com/repos/krlove/eloquent-model-generator/zipball/f4383da4a6b0dd643986330e86fd39d631e569be",
composer.lock:                "krlove/code-generator": "^1.0",
composer.lock:                        "Krlove\\EloquentModelGenerator\\Provider\\GeneratorServiceProvider"
composer.lock:                    "Krlove\\EloquentModelGenerator\\": "src/"
composer.lock:            "description": "Eloquent Model Generator",
composer.lock:                "issues": "https://github.com/krlove/eloquent-model-generator/issues",
composer.lock:                "source": "https://github.com/krlove/eloquent-model-generator/tree/2.0.1"
composer.lock:                "ext-soap": "To be able to generate mocks based on WSDL files",
composer.lock:        "krlove/eloquent-model-generator": 20
```

Full `composer.json`:

```
{
    "name": "laravel/laravel",
    "type": "project",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "require": {
        "php": "^7.3|^8.0",
        "barryvdh/laravel-debugbar": "*",
        "doctrine/dbal": "^3.6",
        "fruitcake/laravel-cors": "^2.0",
        "guzzlehttp/guzzle": "^7.0.1",
        "laravel/framework": "^9.0",
        "laravel/sanctum": "^2.11",
        "laravel/telescope": "^4.15",
        "laravel/tinker": "^2.5",
        "laravel/ui": "*",
        "michaelachrisco/readonly": "^0.50.0",
        "orangehill/iseed": "^3.0",
        "stancl/tenancy": "^3.7",
        "venturedrake/laravel-crm": "^0.18.1",
        "wildside/userstamps": "^2.3"
    },
    "require-dev": {
        "fakerphp/faker": "^1.9.1",
        "kitloong/laravel-migrations-generator": "^6.6",
        "krlove/eloquent-model-generator": "^2.0@dev",
        "laravel/sail": "^1.0.1",
        "mockery/mockery": "^1.4.4",
        "nunomaduro/collision": "^6.1",
        "phpunit/phpunit": "^9.5.10",
        "spatie/laravel-ignition": "^1.0"
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/",
            "Database\\Factories\\": "database/factories/",
            "Database\\Seeders\\": "database/seeders/"
        },
        "files": [
            "app/Helpers/EmbedAssets.php"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "scripts": {
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi"
        ],
        "post-update-cmd": [
            "@php artisan vendor:publish --tag=laravel-assets --ansi --force"
        ],
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi"
        ]
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        }
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true
    },
    "minimum-stability": "dev",
    "prefer-stable": true
}
```

**Comment by kitloong** [comment] 2023-12-10 08:39
Hi @CaraesNaur , thank you.

I can confirm the error is caused by a conflict with `krlove/eloquent-model-generator` DB types registration.
The quick fix for now is to temporarily remove the library, generate migrations, and re-install the library.

Meanwhile, I will look for a way to fix this problem.

**Comment by CaraesNaur** [comment] 2023-12-10 13:45
The correct migrations were made with `krlove/eloquent-model-generator` 1.3.8.

This is happening with 2.0.1.

**Comment by CaraesNaur** [comment] 2023-12-10 14:08
I rolled back `krlove/eloquent-model-generator` to 1.3.8, the migrations are back to what they should be.

**Comment by kitloong** [comment] 2023-12-11 10:21
This is a known issue in https://github.com/krlove/eloquent-model-generator/issues/103.

Closing this as it is not migrations generator issue.

**Closed by kitloong** 2023-12-11 10:21 UTC
