### ISSUE TITLE
Laravel v6 is only compatible with doctrine/dbal 2, in order to use this feature you must require the package "doctrine/dbal:^2.6"

### ISSUE THREAD

**Issue by sekizlipenguen** [kitloong/laravel-migrations-generator#46] opened 2021-09-03 14:13 UTC
vendor/kitloong/laravel-migrations-generator/src/KitLoong/MigrationsGenerator/MigrationsGeneratorSetting.php:63

  protected function getDoctrineDriver()
    64|     {
    65|         if (! class_exists(DoctrineDriver::class)) {
  > 66|             throw new LogicException(
    67|                 'Laravel v6 is only compatible with doctrine/dbal 2, in order to use this feature you must require the package "doctrine/dbal:^2.6".'
    68|             );
    69|         }

**Comment by kitloong** [comment] 2021-09-06 01:09
Hi @sekizlipenguen 

Thanks for the report.
If seems you have installed incorrect `doctrine/dbal` version.
As the message said, Laravel v6 require `doctrine/dbal:^2.6`

`laravel-migrations-generator` supports both `doctrine/dbal` v2 and v3.
Perhaps you need to check your `composer.json` and resolve the dependency conflict.

I will close the issue now. 
However, if you found the issue is caused by this package, please re-open this issue.
If you can provide a full `composer.json` for investigation is even better.

**Closed by kitloong** 2021-09-06 01:09 UTC

**Comment by sekizlipenguen** [comment] 2021-09-13 19:10
Thanks dude!
