### ISSUE TITLE
Unknown database type data requested - sqlite DB

### ISSUE THREAD

**Issue by bldrvnlw** [kitloong/laravel-migrations-generator#132] opened 2022-10-31 14:32 UTC
**Describe the bug**
The following error appears and no migrations are created: 

```
Setting up Tables and Index Migrations

In AbstractPlatform.php line 454:

  Unknown database type data requested, Doctrine\DBAL\Platforms\SqlitePlatform may not support it.
```

**To Reproduce**
Install the package on a laravel 5.8 installation with sqlite as database.

1. Create table celltype 
```
PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE celltype (jobID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
title TEXT,
email TEXT NOT NULL,
snp2gene INTEGER,
snp2geneTitle TEXT,
status TEXT,
created_at DATA NOT NULL);
```
3. Run `php artisan migrate:generate celltype`

**Expected behavior**
A create migration file would be produced

**Screenshots**
None

**Details (please complete the following information):**
 - DB: sqlite3
 - DB Version: 3
 - Laravel Version: 5.8
 - PHP Version: 7.3
 - Migrations Generator Version: 6.4.3

**Additional context**
NA

**Comment by kitloong** [comment] 2022-11-01 13:54
@bldrvnlw Thanks for reporting.

Could you please check your `doctrine/dbal` version?

I too have the same issue if I install `doctrine/dbal` **v3**, if this is the case, you should use `doctrine/dbal` **v2** given you are using a really old version of Laravel. See https://github.com/laravel/framework/blob/5.8/composer.json#L121

Here are my steps to generate migration files successfully.

1. `php74 /opt/homebrew/bin/composer create-project --prefer-dist laravel/laravel blog "5.8.*"`
2. `php74 /opt/homebrew/bin/composer require doctrine/dbal:^2.0`
3. `php74 /opt/homebrew/bin/composer require --dev "kitloong/laravel-migrations-generator"`
4. `php74 artisan migrate:generate`

**Comment by bldrvnlw** [comment] 2022-11-02 13:57
Thanks for the answer! Indeed it's an old version we're in the process of upgrading to a newer Laravel - the generation of the migrations is part of the whole cleanup.

The dbal version on this system is 2.13.9. I'm still getting that error - perhaps another package is the cause. I could post the composer.lock file if that helps

**Comment by kitloong** [comment] 2022-11-02 14:10
@bldrvnlw Please post your `composer.json` to reproduce the issue.

**Comment by bldrvnlw** [comment] 2022-11-04 09:54
Here it is:
```json
{
    "name": "laravel/laravel",
    "config": {
        "preferred-install": "dist",
        "platform": {
            "php": "7.3"
        }
    },
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "type": "project",
    "require": {
        "php": ">=5.6.4 <7.4",
        "laravel/framework": "5.8.*",
        "laravelcollective/html": "5.8.*",
        "guzzlehttp/guzzle": "^6.2",
        "predis/predis": "^1.1",
        "rairlie/laravel-locking-session": "^1.1",
        "laracasts/utilities": "^3.2",
        "laravel/tinker": "^1.0",
        "doctrine/dbal": "2.*"
    },
    "require-dev": {
        "mockery/mockery": "0.9.*",
        "phpunit/phpunit": "7.*",
        "symfony/css-selector": "3.1.*",
        "symfony/dom-crawler": "3.1.*",
        "fakerphp/faker": "^1.19",
        "kitloong/laravel-migrations-generator": "^6.4"
    },
    "autoload": {
        "classmap": [
            "database"
        ],
        "psr-4": {
            "fuma\\": "app/"
        },
        "files": [
            "app/Helper/helpers.php"
        ]
    },
    "autoload-dev": {
        "classmap": [
            "tests/TestCase.php"
        ]
    },
    "scripts": {
        "post-root-package-install": [
            "php -r \"copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "php artisan key:generate"
        ]
    }
}

```

**Comment by kitloong** [comment] 2022-11-05 05:15
Hi @bldrvnlw , thank you for the details.

I have replaced it with your `composer.json`, I am able to generate migrations successfully.

I amended the following to make it work in my local:

```
"psr-4": {
    "App\\": "app/"
},
```

Remove
```
"files": [
    "app/Helper/helpers.php"
]
```

You may have other conflicts in your source code lead to this error. 
I am closing this issue now since this is not the migration generator error.

**Closed by kitloong** 2022-11-05 05:15 UTC
Labels: needs more info

**Comment by bldrvnlw** [comment] 2022-11-07 13:27
Thanks for your help!
